name: Deploy to Glitch

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Glitch
      uses: kanadgupta/glitch-sync@v1.0
      with:
        project-id: ${{ secrets.GLITCH_PROJECT_ID }}
        auth-token: ${{ secrets.GLITCH_AUTH_TOKEN }}
